import type { Metadata } from "next";
import { Roboto} from "next/font/google";
import "./globals.css";
import { Navbar5 } from "./_components/layout/Navbar";
import { Toaster } from "sonner";
import NextAuthProvider from "@/providers/nextauth.provider";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className} h-full antialiased`}
    >
     <NextAuthProvider>
     <Navbar5 />
     </NextAuthProvider>
      <body className="min-h-full flex flex-col">{children}</body>
              <Toaster />

    </html>
  );
}
